/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ASL;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author lopez
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    int xMouse, yMouse;
    public Home() {
        initComponents();
        HomePanel hp = new HomePanel();
        showPanel(hp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Abutton = new javax.swing.JButton();
        Bbutton = new javax.swing.JButton();
        Cbutton = new javax.swing.JButton();
        Dbutton = new javax.swing.JButton();
        Ebutton = new javax.swing.JButton();
        Fbutton = new javax.swing.JButton();
        Gbutton = new javax.swing.JButton();
        Hbutton = new javax.swing.JButton();
        Ibutton = new javax.swing.JButton();
        Jbutton = new javax.swing.JButton();
        Kbutton = new javax.swing.JButton();
        Lbutton = new javax.swing.JButton();
        Mbutton = new javax.swing.JButton();
        Nbutton = new javax.swing.JButton();
        Obutton = new javax.swing.JButton();
        Pbutton = new javax.swing.JButton();
        Qbutton = new javax.swing.JButton();
        Rbutton = new javax.swing.JButton();
        Sbutton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tbutton = new javax.swing.JButton();
        Ubutton = new javax.swing.JButton();
        Vbutton = new javax.swing.JButton();
        Wbutton = new javax.swing.JButton();
        Xbutton = new javax.swing.JButton();
        Ybutton = new javax.swing.JButton();
        Zbutton = new javax.swing.JButton();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Abutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Abutton.setMnemonic('a');
        Abutton.setText("A");
        Abutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Abutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 50, 50));

        Bbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Bbutton.setMnemonic('b');
        Bbutton.setText("B");
        Bbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Bbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 50, 50));

        Cbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Cbutton.setMnemonic('c');
        Cbutton.setText("C");
        Cbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Cbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 50, 50));

        Dbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Dbutton.setMnemonic('d');
        Dbutton.setText("D");
        Dbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Dbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 50, 50));

        Ebutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Ebutton.setMnemonic('e');
        Ebutton.setText("E");
        Ebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Ebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 50, 50));

        Fbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Fbutton.setMnemonic('f');
        Fbutton.setText("F");
        Fbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Fbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 50, 50));

        Gbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Gbutton.setMnemonic('g');
        Gbutton.setText("G");
        Gbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Gbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 50, 50));

        Hbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Hbutton.setMnemonic('h');
        Hbutton.setText("H");
        Hbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Hbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 50, 50));

        Ibutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Ibutton.setMnemonic('i');
        Ibutton.setText("I");
        Ibutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Ibutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, 50, 50));

        Jbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Jbutton.setMnemonic('j');
        Jbutton.setText("J");
        Jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Jbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 50, 50));

        Kbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Kbutton.setMnemonic('k');
        Kbutton.setText("K");
        Kbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Kbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 130, 50, 50));

        Lbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Lbutton.setMnemonic('l');
        Lbutton.setText("L");
        Lbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Lbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 50, 50));

        Mbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Mbutton.setMnemonic('m');
        Mbutton.setText("M");
        Mbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Mbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 190, 50, 50));

        Nbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Nbutton.setMnemonic('n');
        Nbutton.setText("N");
        Nbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Nbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 50, 50));

        Obutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Obutton.setMnemonic('o');
        Obutton.setText("O");
        Obutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Obutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 70, 50, 50));

        Pbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Pbutton.setMnemonic('p');
        Pbutton.setText("P");
        Pbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Pbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 50, 50));

        Qbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Qbutton.setMnemonic('q');
        Qbutton.setText("Q");
        Qbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Qbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 50, 50));

        Rbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Rbutton.setMnemonic('r');
        Rbutton.setText("R");
        Rbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Rbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 50, 50));

        Sbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Sbutton.setMnemonic('s');
        Sbutton.setText("S");
        Sbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Sbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 50, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1145, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 40));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel2.setText("Note: This program is made for right handed signers");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 770, 480, -1));

        Tbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Tbutton.setMnemonic('t');
        Tbutton.setText("T");
        Tbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Tbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 50, 50));

        Ubutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Ubutton.setMnemonic('u');
        Ubutton.setText("U");
        Ubutton.setToolTipText("");
        Ubutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Ubutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 50, 50));

        Vbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Vbutton.setMnemonic('v');
        Vbutton.setText("V");
        Vbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Vbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 50, 50));

        Wbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Wbutton.setMnemonic('w');
        Wbutton.setText("W");
        Wbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Wbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 50, 50));

        Xbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Xbutton.setMnemonic('x');
        Xbutton.setText("X");
        Xbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Xbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 50, 50));

        Ybutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Ybutton.setMnemonic('y');
        Ybutton.setText("Y");
        Ybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Ybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 50, 50));

        Zbutton.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Zbutton.setMnemonic('z');
        Zbutton.setText("Z");
        Zbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(Zbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 50, 50));

        content.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1190, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1190, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x- xMouse,y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
       xMouse = evt.getX();
       yMouse = evt.getY();
       // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MousePressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
       jPanel3.setBackground(Color.red);
       jLabel3.setForeground(Color.white);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel3MouseExited

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(Color.white);
               jLabel3.setForeground(Color.black);
    }//GEN-LAST:event_jLabel3MouseExited

    private void CbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbuttonActionPerformed
        // TODO add your handling code here:
        CPanel cp = new CPanel();
        showPanel(cp);
    }//GEN-LAST:event_CbuttonActionPerformed

    private void EbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EbuttonActionPerformed
        // TODO add your handling code here:
        EPanel ep = new EPanel();
        showPanel(ep);
    }//GEN-LAST:event_EbuttonActionPerformed

    private void GbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GbuttonActionPerformed
        // TODO add your handling code here:
        GPanel gp = new GPanel();
        showPanel(gp);
    }//GEN-LAST:event_GbuttonActionPerformed

    private void LbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LbuttonActionPerformed
        // TODO add your handling code here:
        LPanel lp = new LPanel();
        showPanel(lp);
    }//GEN-LAST:event_LbuttonActionPerformed

    private void AbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbuttonActionPerformed
        // TODO add your handling code here:
        APanel ap = new APanel();
        showPanel(ap);
    }//GEN-LAST:event_AbuttonActionPerformed

    private void BbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BbuttonActionPerformed
        // TODO add your handling code here:
        BPanel bp = new BPanel();
        showPanel(bp);
    }//GEN-LAST:event_BbuttonActionPerformed

    private void DbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DbuttonActionPerformed
        // TODO add your handling code here:
        DPanel dp = new DPanel();
        showPanel(dp);
    }//GEN-LAST:event_DbuttonActionPerformed

    private void JbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbuttonActionPerformed
        // TODO add your handling code here:
        jPanel jp = new jPanel();
        showPanel(jp);
    }//GEN-LAST:event_JbuttonActionPerformed

    private void IbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IbuttonActionPerformed
        // TODO add your handling code here:'
        IPanel ip = new IPanel();
        showPanel(ip);
    }//GEN-LAST:event_IbuttonActionPerformed

    private void SbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SbuttonActionPerformed
        // TODO add your handling code here:
            SPanel sp = new SPanel();
        showPanel(sp);
    }//GEN-LAST:event_SbuttonActionPerformed

    private void RbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbuttonActionPerformed
        // TODO add your handling code here:
            RPanel rp = new RPanel();
        showPanel(rp);
    }//GEN-LAST:event_RbuttonActionPerformed

    private void QbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QbuttonActionPerformed
        // TODO add your handling code here:
            QPanel qp = new QPanel();
        showPanel(qp);
    }//GEN-LAST:event_QbuttonActionPerformed

    private void PbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PbuttonActionPerformed
        // TODO add your handling code here:
            PPanel pp = new PPanel();
        showPanel(pp);
    }//GEN-LAST:event_PbuttonActionPerformed

    private void ObuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObuttonActionPerformed
        // TODO add your handling code here:
            OPanel op = new OPanel();
        showPanel(op);
    }//GEN-LAST:event_ObuttonActionPerformed

    private void ZbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZbuttonActionPerformed
        // TODO add your handling code here:
        ZPanel zp = new ZPanel();
        showPanel(zp);
    }//GEN-LAST:event_ZbuttonActionPerformed

    private void YbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YbuttonActionPerformed
        // TODO add your handling code here:
        YPanel yp = new YPanel();
        showPanel(yp);
    }//GEN-LAST:event_YbuttonActionPerformed

    private void XbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XbuttonActionPerformed
        // TODO add your handling code here:
        XPanel xp = new XPanel();
        showPanel(xp);
    }//GEN-LAST:event_XbuttonActionPerformed

    private void WbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WbuttonActionPerformed
        // TODO add your handling code here:
        WPanel wp = new WPanel();
        showPanel(wp);
    }//GEN-LAST:event_WbuttonActionPerformed

    private void VbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VbuttonActionPerformed
        // TODO add your handling code here:
        VPanel vp = new VPanel();
        showPanel(vp);
    }//GEN-LAST:event_VbuttonActionPerformed

    private void UbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbuttonActionPerformed
        // TODO add your handling code here:
        UPanel up = new UPanel();
        showPanel(up);
    }//GEN-LAST:event_UbuttonActionPerformed

    private void TbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbuttonActionPerformed
        // TODO add your handling code here:
        TPanel tp = new TPanel();
        showPanel(tp);
    }//GEN-LAST:event_TbuttonActionPerformed

    private void NbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NbuttonActionPerformed
        // TODO add your handling code here:
        NPanel np = new NPanel();
        showPanel(np);
    }//GEN-LAST:event_NbuttonActionPerformed

    private void MbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MbuttonActionPerformed
        // TODO add your handling code here:
        MPanel mp = new MPanel();
        showPanel(mp);
    }//GEN-LAST:event_MbuttonActionPerformed

    private void KbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KbuttonActionPerformed
        // TODO add your handling code here:
        KPanel kp = new KPanel();
        showPanel(kp);
    }//GEN-LAST:event_KbuttonActionPerformed

    private void HbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HbuttonActionPerformed
        // TODO add your handling code here:
        HPanel hp = new HPanel();
        showPanel(hp);
    }//GEN-LAST:event_HbuttonActionPerformed

    private void FbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FbuttonActionPerformed
        // TODO add your handling code here:
        FPanel fp = new FPanel();
        showPanel(fp);
    }//GEN-LAST:event_FbuttonActionPerformed
    private void showPanel(JPanel p){
         
        p.setSize(1170,520);
        p.setLocation(0,0);
        
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Abutton;
    private javax.swing.JButton Bbutton;
    private javax.swing.JButton Cbutton;
    private javax.swing.JButton Dbutton;
    private javax.swing.JButton Ebutton;
    private javax.swing.JButton Fbutton;
    private javax.swing.JButton Gbutton;
    private javax.swing.JButton Hbutton;
    private javax.swing.JButton Ibutton;
    private javax.swing.JButton Jbutton;
    private javax.swing.JButton Kbutton;
    private javax.swing.JButton Lbutton;
    private javax.swing.JButton Mbutton;
    private javax.swing.JButton Nbutton;
    private javax.swing.JButton Obutton;
    private javax.swing.JButton Pbutton;
    private javax.swing.JButton Qbutton;
    private javax.swing.JButton Rbutton;
    private javax.swing.JButton Sbutton;
    private javax.swing.JButton Tbutton;
    private javax.swing.JButton Ubutton;
    private javax.swing.JButton Vbutton;
    private javax.swing.JButton Wbutton;
    private javax.swing.JButton Xbutton;
    private javax.swing.JButton Ybutton;
    private javax.swing.JButton Zbutton;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
